### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jackcarlisle** [louishardy/LouisHardyPhotography#1]
Hey mate, just took a look through your file tree and I've got a couple of suggestions for you:

## TODO:

- [ ] change all folder and file names to lowercase/camelcase/snakecase `Public` -> `public`, `Aboutme.html` -> `aboutMe.html` (camelcase) or `about_me.html` (snakecase)

- [ ] create separate folders within your `public` directory for each of `html`, `js`, `css` and then put all the relevant files with their respective folders:
```
public
    |_css
       |_style.css
    |_html
        |_index.html
        |_aboutMe.html
    |_js
        |_index.js
```

- [ ] get rid of your `index.js` file inside your `public` folder
